"use client";

import EarthProtocolLogo from "@/assets/logos/earth-protocol.png";
import { ConnectButton, RainbowKitProvider } from "@rainbow-me/rainbowkit";
import "@rainbow-me/rainbowkit/styles.css";
import { Inter } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import { WagmiConfig } from "wagmi";

import { chains, wagmiConfig } from "@/config/wagmi";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<WagmiConfig config={wagmiConfig}>
					<RainbowKitProvider chains={chains}>
						<Link href="/">
							<Image
								alt="earth-protocol-logo"
								src={EarthProtocolLogo.src}
								width={EarthProtocolLogo.width}
								height={EarthProtocolLogo.height}
							/>
						</Link>
						<ConnectButton />
						{children}
					</RainbowKitProvider>
				</WagmiConfig>
			</body>
		</html>
	);
}
